### ISSUE TITLE
Problem in running

### ISSUE THREAD

**Issue by Paptoos** [parsampsh/pashmak#10]
I use this code to run pashmak
```
python src/pashmak.py test.pashm
```
But I have this error :
```
RuntimeError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<string>, line 1):
        in <system>:2: $__file__ = "C:\Users\Amirmohammad Ghazi\Desktop\pashmak-0.5.2\test.pashm"
```
test.pashm is this :
```
mem 'something to print\n'; # first operation
out ^; # second operation
```
Windows : 10
Build : 2009
Terminal : windows default cmd
Pashmak version : 0.5.2
Python Version : 3.8.5

**Comment by parsampsh** [comment]
Oh yes. i know this problem is from what(Only is on windows). Thank you for your report paptoos. i'll fix this and release 0.5.3

**Comment by Paptoos** [comment]
Thanks

**Comment by parsampsh** [comment]
I commited. please pull and check again and tell me the result.

**Comment by Paptoos** [comment]
Error fixed , Thanks
