### ISSUE TITLE
import modules

### ISSUE THREAD

**Issue by Paptoos** [parsampsh/pashmak#5]
Hello
now to import sys code is :
import '@sys'
it is better :
import @sys
or :
import sys

**Comment by parsampsh** [comment]
hello Paptoos! this is very good idea. I'll add this feature (import @modulename without quotes) for the new release (0.5).

Thank you so much!

**Comment by parsampsh** [comment]
Added :)

**Comment by Paptoos** [comment]
Thanks 
I closed this issue
