### ISSUE TITLE
Paradigm and type system of Pashmak programming language

### ISSUE THREAD

**Issue by sami2020pro** [parsampsh/pashmak#6]
I want to know more about **Pashmak programming language** and I want to write a lot of **libraries** for this language.
But first i wanna know what the **paradigms** and **type systems** of this language are ?
(this language is very simple and I write a simple **ASCII** and **ANSI** Terminal Color for Pashmak and I can contribute and write good libraries)

**Comment by parsampsh** [comment]
Hello Sami. I'm glad that this language has come to your attention and you want to write a library for it. Pashmak language is a procedural language. It is not object-oriented and does not have if and loop structures directly (but these structures can be implemented using sections). Pashmak executes commands line by line.
For example, we can not use the function defined in the bottom lines in our code. This means that Pashmak does not take a general look at the code at first. It starts from the first line. As I said, the Pashmak paradigm is procedural and has no class. You can only use the namespace to segment the program, which does not replace the class. It is also possible to import code from other files or from libraries.
The structure of Pashmak evalution is exactly Python. For example in the code
```bash
println 2 + 2
```
The phrase `2 + 2` is sent to Python. This means all data types and operator structures, etc. in the form of Python. for example:
```bash
println str($some_int_var) + ' is number'
```
This code uses the Python `str` function.
also you can look the `examples` and `Pashmak Internal Modules` to know more.
I hope my explanation was useful.

**Comment by sami2020pro** [comment]
It was good information.
I have **four** questions now:
pashmak Does it have a manager package like gem, pip and cargo?
Does Pashmak contribute guide like straight, cloak or other things?
Are changes such as adding a new system type to improve pashmak like static type possible? Or bootstrapping in the future, for example.
Do you advance the pashmak language with the software release cycle?

(I have the ability to help this language and I like it)

**Comment by parsampsh** [comment]
> It was good information.
> I have **four** questions now:
> pashmak Does it have a package manager like gem, pip and cargo?
> Does Pashmak contribute guide like rust, clojure or other things?
> Are changes such as adding a new type system to improve pashmak like static type possible? Or bootstrapping in the future, for example.
> Do you advance the pashmak language with the software release cycle?
> 
> (I have the ability to help this language and I like it)

- So, Pashmak haven't package manager(I wanted to write a package manager named `parham` for that, but I regretted it because there was not any library (: ).

- Yes, Pashmak has Contributing Guide line. you can full Read documentation and [Contributing Guide](https://github.com/parsampsh/pashmak/blob/master/CONTRIBUTING.md).

- So, actually i think Pashmak is a simple language and has not Potential for something like this.

- Yes I do.

**Comment by sami2020pro** [comment]
So good.
I created a library but i have one problem in Pashmak, i haven't any access to the variables at other files and namespaces, Now how can I access those variables ?

**Comment by parsampsh** [comment]
So, Variables are isolated in modules.
you can declare a variable publicly with `gset` command:

```bash
gset 'public_var_name', <the value>
```
actually, I don't have any idea to make it better. for example is good something like this?:

```bash
public $varname = <value>;
```

**Comment by sami2020pro** [comment]
Thanks,
hoom, not bad and not good, but i loved ;)

**Comment by parsampsh** [comment]
> So good.
> I created a library but i have one problem in Pashmak, i haven't any access to the variables at other files and namespaces, Now how can I access those variables ?

SO, I checked this more, This is a Bug and i created A [Bugfix branch for this](https://github.com/parsampsh/pashmak/tree/bugfix/fix-importing-variables-error).

I will fix this bug.

**Comment by sami2020pro** [comment]
This is good, you can write a example for gset, i get invalid syntax.

**Comment by sami2020pro** [comment]
If the bug fixes, I will release this library (Terminal Color and more...)

**Comment by parsampsh** [comment]
Fixed.

**Comment by parsampsh** [comment]
Use 0.5.1 (bug is fixed in this release).

**Comment by sami2020pro** [comment]
thanks

**Comment by sami2020pro** [comment]
Ok
I write the library at [here](https://github.com/sami2020pro/polor-pashm), Now you can see the **polor** library for Terminal Color.
But polor have one problem and you can see and test that on `polor_test.pashm` file.

**Comment by parsampsh** [comment]
Thank you so much sami. this is perfect! can I add a link to your repository in documentation?

**Comment by sami2020pro** [comment]
Of course you can do the same.

**Comment by parsampsh** [comment]
Added in [here](https://github.com/parsampsh/pashmak/#another-useful-libraries-written-by-others) :)

**Comment by sami2020pro** [comment]
Thanks,
If Pashmak can progress, I will write more libraries and help Pashmak progress. (for example binding x11, graphics, framework and more)

**Comment by parsampsh** [comment]
Thanks sami. issue can be closed?

**Comment by sami2020pro** [comment]
yes
