### ISSUE TITLE
python namespace or pycode

### ISSUE THREAD

**Issue by Paptoos** [parsampsh/pashmak#8]
now we can use python code in pashmak without adding any namespace
my idea is we can not use python code default and use pycode function or using a namespace
like this :
```
str(2)
```
is better :
``` 
import @pycode
str(2)
```
or :
```
pycode(str(2))
````

**Comment by parsampsh** [comment]
so, actually `python` function for running python codes is used by all of internal libraries and is very important and is a internal function. this function should be accessible in everywhere and we cannot transfer this to a module.
