### ISSUE TITLE
Any idea about package manager for pashmak?

### ISSUE THREAD

**Issue by parsampsh** [parsampsh/pashmak#9]
hi friends. have you any idea or suggestion about a package manager for pashmak libraries?

**Comment by parsampsh** [comment]
@sami2020pro @paptoos

**Comment by Paptoos** [comment]
Hi 
now pashmak have just one library
If pashmak have a lot of libraries , can have a package manager
I think start with library installer to can install libraries to do not use libraries source in apps

**Comment by sami2020pro** [comment]
yes this is good **idea**.

**Comment by parsampsh** [comment]
actually, libraries can be installed manual. for example we can create a directory in `/usr/lib/pashmak_modules/mylibrary/` and put our library scripts in that. next we can import that with `import @mylibrary`. I think this is good idea and a **library installer** for start is good. anyway, I think `parham` is a good name for that :)

**Comment by sami2020pro** [comment]
like ruby

**Comment by parsampsh** [comment]
> Like **Ruby**

I didn't work with the ruby, but maybe something like that :)

**Comment by parsampsh** [comment]
I think we have important works more than package manager and this is not needed for now. maybe later :)
